### ISSUE TITLE
Chrome version 71 - Android 8.1.0

### ISSUE THREAD

**Issue by rcpassos** [LivotovLabs/3DSView#21]
Hi,

I'm using Android 8.1.0 and the Chrome Webview version is 71 and I'm not getting the md and paRes parameters from the D3SSViewAuthorizationListener on onAuthorizationCompleted, but if I use Chrome Webview version 70 it will work fine.

Can you help me?

Thanks.

**Comment by sandyscoffable** [comment]
There is a PR and discussion for this over here: https://github.com/LivotovLabs/3DSView/pull/20
