### ISSUE TITLE
PDS2 (3-D Secure v2)

### ISSUE THREAD

**Issue by sandyscoffable** [LivotovLabs/3DSView#27]
I've got a working version of the library that I've (accidentally) included in https://github.com/LivotovLabs/3DSView/pull/26 (as I committed to master on my own fork, and there was already a PR from master into this repository).

This supports the fallback to 3-D Secure v1. Feel free to change! 😄

**Comment by livotov** [comment]
Thanks and sorry for such a long response. Merged now
