### ISSUE TITLE
Migrate to androidX

### ISSUE THREAD

**Issue by doniwinata0309** [LivotovLabs/3DSView#28]
Any plan to migrate legacy support package to use androidX ? 
By moving the library to androidX, we can disable jetifier and make some improvement on the build speed.

**Comment by mezpahlan** [comment]
#26 satisfies this requirement. In addition #29 removed any need for this requirement. The library is actually pretty simple and doesn't need many dependencies further than what is available in API of the Android SDK.

In other words I think this is can be closed. Do you agree @livotov ?
