### ISSUE TITLE
Consider using maven central or SSL

### ISSUE THREAD

**Issue by lkorth** [LivotovLabs/3DSView#5]
Serving code over HTTP can be [very insecure](http://blog.ontoillogical.com/blog/2014/07/28/how-to-take-over-any-java-developer/). Please consider adding an SSL certificate to your host and redirecting to the HTTPS version or better yet pushing it up to maven central.

**Comment by livotov** [comment]
just moved release packages to jcenter as it is now simple process in comparison to maven central bureaucracy :)

**Comment by livotov** [comment]
p.s. please allow 1 business day to become it visible there for the first time. Before that you can access it from bintray repsoitory, see the readme.md file for url.
